from fpdf import FPDF
import time
import os
import re
import math

class AdvancedPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 10)
        self.set_text_color(100, 116, 139) # Slate 500
        self.cell(0, 10, 'CONFIDENTIAL SECURITY AUDIT', 0, 0, 'L')
        self.set_text_color(220, 38, 38) # Sentinel Red
        self.cell(0, 10, 'SENTINEL INTELLIGENCE', 0, 1, 'R')
        
        self.set_draw_color(220, 38, 38)
        self.set_line_width(0.5)
        self.line(10, 20, 200, 20)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by Sentinel', 0, 0, 'C')

    def draw_metric_card(self, x, y, w, h, title, value, subtitle, color):
        self.set_xy(x, y)
        self.set_fill_color(255, 255, 255)
        self.set_draw_color(226, 232, 240)
        self.rect(x, y, w, h, 'DF')
        self.set_fill_color(*color)
        self.rect(x, y, 2, h, 'F')
        
        self.set_xy(x + 5, y + 5)
        self.set_font('Arial', 'B', 9)
        self.set_text_color(148, 163, 184)
        self.cell(w-10, 5, title.upper(), 0, 2)
        
        self.set_font('Arial', 'B', 16)
        self.set_text_color(15, 23, 42)
        self.cell(w-10, 8, value, 0, 2)
        
        self.set_font('Arial', '', 7)
        self.set_text_color(100, 116, 139)
        self.cell(w-10, 5, subtitle, 0, 0)

    def draw_severity_chart(self, x, y, w, h, summary):
        total = summary['high'] + summary['medium'] + summary['low']
        if total == 0: total = 1
        
        high_w = (summary['high'] / total) * w
        med_w = (summary['medium'] / total) * w
        low_w = (summary['low'] / total) * w
        
        self.set_xy(x, y)
        self.set_fill_color(241, 245, 249)
        self.rect(x, y, w, h, 'F')
        
        current_x = x
        if high_w > 0:
            self.set_fill_color(220, 38, 38)
            self.rect(current_x, y, high_w, h, 'F')
            current_x += high_w
            
        if med_w > 0:
            self.set_fill_color(249, 115, 22)
            self.rect(current_x, y, med_w, h, 'F')
            current_x += med_w
            
        if low_w > 0:
            self.set_fill_color(22, 163, 74)
            self.rect(current_x, y, low_w, h, 'F')

        self.set_xy(x, y + h + 2)
        self.set_font('Arial', 'B', 8)
        self.set_text_color(100, 116, 139)
        self.cell(w, 5, f"THREAT LANDSCAPE: {int((summary['high']/total)*100)}% CRITICAL | {int((summary['medium']/total)*100)}% MODERATE | {int((summary['low']/total)*100)}% LOW", 0, 0, 'C')

    def draw_code_block(self, code_text):
        self.set_font('Courier', '', 8)
        self.set_fill_color(245, 247, 250) 
        self.set_draw_color(226, 232, 240) 
        
        lines = code_text.split('\n')
        h = (len(lines) * 4) + 6
        
        x = self.get_x()
        y = self.get_y()
        self.rect(x, y, 190, h, 'FD')
        
        self.set_xy(x + 2, y + 3)
        self.set_text_color(51, 65, 85) 
        self.multi_cell(186, 4, code_text)
        
        self.set_y(y + h + 2)

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 14)
        self.set_text_color(15, 23, 42)
        self.cell(0, 10, label, 0, 1, 'L')
        self.ln(2)

    def sub_title(self, label):
        self.set_font('Arial', 'B', 11)
        self.set_text_color(51, 65, 85)
        self.cell(0, 8, label, 0, 1, 'L')

    def body_text(self, text):
        self.set_font('Arial', '', 10)
        self.set_text_color(51, 65, 85)
        self.multi_cell(0, 5, text)
        self.ln()

# --- BUSINESS LOGIC ---
def calculate_business_metrics(summary, vulnerabilities):
    financial_risk = (summary['high'] * 75000) + (summary['medium'] * 15000) + (summary['low'] * 2000)
    
    vuln_types = [v.get('type', '').lower() for v in vulnerabilities]
    
    if any("sql" in v for v in vuln_types):
        financial_risk *= 2.5 
        
    if any("pii" in v for v in vuln_types):
        financial_risk *= 1.5 
        
    if any("secret" in v or "env" in v for v in vuln_types):
        financial_risk *= 3.0 

    hours = (summary['high'] * 12) + (summary['medium'] * 6) + (summary['low'] * 2)
    dev_days = max(1, math.ceil(hours / 8))
    
    prob = 10
    if summary['high'] > 0: prob = 95
    elif summary['medium'] > 2: prob = 75
    elif summary['medium'] > 0: prob = 45
    elif summary['low'] > 0: prob = 20
    
    return financial_risk, dev_days, prob

def get_grade_info(summary):
    if summary['high'] > 0:
        return "F", (220, 38, 38), "CRITICAL EXPOSURE", "Emergency Patching Required"
    elif summary['medium'] > 2:
        return "C", (249, 115, 22), "ELEVATED RISK", "Plan Remediation Sprint"
    elif summary['medium'] > 0:
        return "B", (234, 179, 8), "MODERATE POSTURE", "Hardening Recommended"
    else:
        return "A", (22, 163, 74), "SECURE", "Continue Monitoring"

# --- CONTEXT-AWARE SUMMARY GENERATOR ---
def generate_dynamic_summary(report_data):
    summary = report_data.get('summary', {})
    vulns = report_data.get('vulnerabilities', [])
    vuln_types = [v.get('type', '') for v in vulns]
    target = report_data.get('target', 'Target System')

    text = f"Sentinel Intelligence performed a deep-dive security audit on {target}. "
    if summary['high'] > 0:
        text += f"The system is currently in a CRITICAL state, with {summary['high']} high-severity vulnerabilities identified that pose an immediate threat to business continuity. "
    elif summary['medium'] > 0:
        text += f"The system demonstrates moderate security maturity but contains {summary['medium']} significant gaps that could be chained by attackers. "
    else:
        text += "The system demonstrates a strong security posture with no immediate critical threats detected. "

    highlights = []
    
    if any("SQL" in t for t in vuln_types):
        highlights.append("CRITICAL: Database integrity is compromised. Active SQL Injection vectors were detected.")
    
    if any("XSS" in t for t in vuln_types):
        highlights.append("Client-side security is weak. Reflected XSS vulnerabilities were found.")
        
    if any("Sensitive File" in t or "Secret" in t or "PII" in t for t in vuln_types):
        highlights.append("INFRASTRUCTURE LEAK: Critical configuration files or PII data are publicly accessible.")

    if any("Shadow" in t for t in vuln_types):
        highlights.append("Undocumented 'Shadow APIs' were discovered.")

    if highlights:
        text += "\n\nKEY FINDINGS:\n" + " ".join(highlights)
    else:
        text += "\n\nRoutine hygiene upgrades are recommended to maintain this status."

    text += "\n\nIt is recommended to distribute the attached Technical Findings Matrix to the engineering team immediately."
    return text

def generate_dynamic_actions(vulns):
    actions = []
    vuln_types = [v.get('type', '') for v in vulns]
    
    if any("SQL" in t for t in vuln_types):
        actions.append("URGENT: Implement Prepared Statements (Parameterized Queries) for all database interactions.")
    
    if any("Secret" in t or "File" in t for t in vuln_types):
        actions.append("IMMEDIATE: Rotate all API keys and database credentials. Configure server to block access to dotfiles (.env, .git).")
        
    if any("XSS" in t for t in vuln_types):
        actions.append("Sanitize all user inputs using a library like DOMPurify and implement a strict Content-Security-Policy (CSP).")
        
    if any("Shadow" in t for t in vuln_types):
        actions.append("Audit: Catalog detected Shadow APIs and enforce JWT authentication on these routes.")
        
    if not actions:
        actions.append("Conduct a quarterly penetration test.")
        actions.append("Review IAM permissions.")
        actions.append("Update third-party dependencies.")
        
    return actions


# --- OSINT RECON GENERATOR ---
def generate_recon_report(report_data):
    """Generates an Enterprise Intelligence Report for OSINT data using ReportLab."""
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors

    target = report_data.get('target', 'Unknown Domain')
    infra = report_data.get('infrastructure', [])
    
    # Ensure reports directory exists
    if not os.path.exists("reports"):
        os.makedirs("reports")
        
    filename = f"reports/Sentinel_OSINT_Report_{int(time.time())}.pdf"
    filepath = os.path.join(os.getcwd(), filename)
    
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []
    
    # Custom Styles
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=22, textColor=colors.HexColor('#2563eb'), spaceAfter=15)
    header_style = ParagraphStyle('Header', parent=styles['Heading2'], textColor=colors.HexColor('#333333'))
    playbook_style = ParagraphStyle('Playbook', parent=styles['Normal'], leftIndent=20, textColor=colors.HexColor('#555555'))
    
    # Title Block
    elements.append(Paragraph("CONFIDENTIAL INTELLIGENCE AUDIT", title_style))
    elements.append(Paragraph(f"<b>Target Scope:</b> {target}", styles['Normal']))
    elements.append(Paragraph(f"<b>Total Assets Discovered:</b> {len(infra)}", styles['Normal']))
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("1. Attack Surface Matrix", header_style))
    elements.append(Spacer(1, 10))
    
    # Loop through the discovered infrastructure and build the Dossiers
    for idx, node in enumerate(infra, 1):
        subdomain = node.get('subdomain', 'N/A')
        ip = node.get('ip', 'N/A')
        status = node.get('status', 'Offline')
        intel = node.get('intel', {})
        risk = intel.get('risk', 'Low')
        
        elements.append(Paragraph(f"{idx}. {subdomain}", styles['Heading3']))
        
        status_text = f"<b>Resolution IP:</b> {ip} | <b>HTTP Status:</b> {status} | "
        if risk == "Critical":
            elements.append(Paragraph(status_text + f"<font color='red'><b>Risk: {risk}</b></font>", styles['Normal']))
        elif risk == "High":
            elements.append(Paragraph(status_text + f"<font color='orange'><b>Risk: {risk}</b></font>", styles['Normal']))
        else:
            elements.append(Paragraph(status_text + f"<b>Risk: {risk}</b>", styles['Normal']))
            
        elements.append(Paragraph(f"<b>Classification:</b> {intel.get('title', 'Unknown Node')}", styles['Normal']))
        elements.append(Spacer(1, 5))
        
        elements.append(Paragraph("<b>The Hacker's Playbook:</b>", styles['Normal']))
        elements.append(Paragraph(intel.get('playbook', 'Standard network node. Monitor for exposed ports.'), playbook_style))
        elements.append(Spacer(1, 5))
        
        elements.append(Paragraph("<b>DevSecOps Remediation:</b>", styles['Normal']))
        elements.append(Paragraph(intel.get('remediation', 'Ensure standard firewall and patch management policies apply.'), playbook_style))
        
        elements.append(Spacer(1, 25))
        
    doc.build(elements)
    return filepath


# --- QUARANTINE REPORT GENERATOR ---
def generate_quarantine_report(report_data):
    target = report_data.get('target', 'Unknown Artifact')
    malicious_count = report_data.get('malicious_count', 0)
    total_engines = report_data.get('total_engines', 72)
    engines = report_data.get('engine_results', [])
    explanation = report_data.get('threat_explanation', 'No threat intelligence summary provided.')
    scan_type = report_data.get('scanType', 'hash')
    
    pdf = AdvancedPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Title
    pdf.set_font('Arial', 'B', 24)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, "QUARANTINE CONTAINMENT REPORT", 0, 1, 'L')
    
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 6, f"Analyzed Artifact: {target}", 0, 1, 'L')
    pdf.cell(0, 6, f"Artifact Type: {scan_type.upper()}", 0, 1, 'L')
    pdf.cell(0, 6, f"Report Date: {time.strftime('%Y-%m-%d %H:%M:%S')}", 0, 1, 'L')
    pdf.ln(10)
    
    # Status Scorecard
    is_malicious = malicious_count > 0
    status_text = "MALICIOUS ARTIFACT" if is_malicious else "CLEAN ARTIFACT"
    color = (220, 38, 38) if is_malicious else (22, 163, 74)
    
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(*color)
    pdf.rect(10, pdf.get_y(), 190, 30, 'FD')
    
    pdf.set_xy(15, pdf.get_y() + 8)
    pdf.set_font('Arial', 'B', 18)
    pdf.set_text_color(*color)
    pdf.cell(80, 10, status_text, 0, 0, 'L')
    
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(100, 10, f"Detection Ratio: {malicious_count} / {total_engines} Engines", 0, 1, 'R')
    pdf.ln(15)
    
    # Intelligence Summary
    pdf.chapter_title("Threat Intelligence Summary")
    if is_malicious:
        pdf.set_text_color(220, 38, 38)
    else:
        pdf.set_text_color(22, 163, 74)
    pdf.set_font('Arial', '', 11)
    pdf.multi_cell(0, 6, explanation)
    pdf.ln(10)
    
    # Engine Signatures
    pdf.chapter_title("Detailed Security Signatures")
    if engines:
        for i, e in enumerate(engines, 1):
            if pdf.get_y() > 250: pdf.add_page()
            
            pdf.set_fill_color(254, 242, 242)
            pdf.rect(10, pdf.get_y(), 190, 8, 'F')
            
            pdf.set_font('Arial', 'B', 10)
            pdf.set_text_color(15, 23, 42)
            pdf.cell(10, 8, str(i), 0, 0, 'C')
            pdf.cell(60, 8, e.get('engine', 'Unknown Engine'), 0, 0)
            
            pdf.set_font('Courier', 'B', 9)
            pdf.set_text_color(220, 38, 38)
            pdf.cell(110, 8, e.get('result', 'Malicious'), 0, 1)
            pdf.ln(2)
    else:
        pdf.set_font('Arial', '', 10)
        pdf.set_text_color(51, 65, 85)
        pdf.body_text("No malicious signatures were triggered during analysis.")
        
    if not os.path.exists("reports"):
        os.makedirs("reports")
        
    filename = f"reports/Sentinel_Quarantine_{int(time.time())}.pdf"
    pdf.output(filename)
    return filename


# --- MAIN GENERATOR ---
def generate_report(report_data, report_type='technical'):
    # 1. IMMEDIATE ROUTING: Divert specialized reports directly to their engines
    if report_type == 'recon':
        return generate_recon_report(report_data)
    elif report_type == 'quarantine':
        return generate_quarantine_report(report_data)
        
    # 2. DAST REPORT GENERATION: Proceed with FPDF for Executive/Technical scans
    pdf = AdvancedPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    vulns = report_data.get('vulnerabilities', [])
    summary = report_data.get('summary', {'high': 0, 'medium': 0, 'low': 0})
    target = report_data.get('target', 'Unknown')

    # --- TITLE PAGE HEADER ---
    title_prefix = "EXECUTIVE STRATEGY" if report_type == 'executive' else "TECHNICAL AUDIT"
    pdf.set_font('Arial', 'B', 24)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, f"{title_prefix} REPORT", 0, 1, 'L')
    
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 6, f"Target Asset: {target}", 0, 1, 'L')
    pdf.cell(0, 6, f"Scan Date: {time.strftime('%Y-%m-%d')}", 0, 1, 'L')
    pdf.ln(10)

    # --- SCORECARD (Both Reports) ---
    grade, color, grade_title, grade_action = get_grade_info(summary)
    
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    pdf.rect(10, pdf.get_y(), 190, 35, 'FD')
    
    current_y = pdf.get_y()
    pdf.set_fill_color(255, 255, 255)
    pdf.set_draw_color(*color)
    pdf.set_line_width(1)
    pdf.ellipse(13, current_y + 5.5, 24, 24, 'FD')
    
    pdf.set_xy(13, current_y + 11)
    pdf.set_font('Arial', 'B', 24)
    pdf.set_text_color(*color)
    pdf.cell(24, 13, grade, 0, 0, 'C')
    
    pdf.set_xy(45, current_y + 8)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(100, 6, grade_title, 0, 2)
    
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(100, 6, grade_action, 0, 0)
    pdf.ln(40)

    # --- DYNAMIC METRICS ---
    pdf.ln(5)
    fin_risk, dev_days, prob = calculate_business_metrics(summary, vulns)
    
    start_x = 10
    card_w = 60
    card_h = 30
    gap = 5
    y_pos = pdf.get_y()
    
    pdf.draw_metric_card(start_x, y_pos, card_w, card_h, "Est. Financial Risk", f"${fin_risk:,.0f}", "Potential liability", (220, 38, 38))
    pdf.draw_metric_card(start_x + card_w + gap, y_pos, card_w, card_h, "Dev Time to Fix", f"{dev_days} Days", "Estimated effort", (249, 115, 22))
    pdf.draw_metric_card(start_x + (card_w + gap)*2, y_pos, card_w, card_h, "Breach Probability", f"{prob}%", "AI Risk Score", (37, 99, 235))
    
    pdf.set_y(y_pos + card_h + 10)

    # ================= EXECUTIVE REPORT =================
    if report_type == 'executive':
        pdf.ln(5)
        pdf.chapter_title("Threat Visualization")
        pdf.draw_severity_chart(10, pdf.get_y(), 190, 8, summary)

        pdf.ln(15)
        pdf.chapter_title("1. Business Impact Analysis")
        pdf.body_text(f"This report outlines the security posture of {target}. The findings below represent risks to data integrity, customer trust, and operational continuity.")
        
        # Group by severity for high-level overview
        critical_vulns = [v for v in vulns if v.get('severity') in ['High', 'Critical']]
        
        if critical_vulns:
            for v in critical_vulns:
                pdf.ln(5)
                # Title
                pdf.set_font('Arial', 'B', 11)
                pdf.set_text_color(220, 38, 38)
                pdf.cell(0, 6, f"[{v.get('severity', 'UNK').upper()}] {v.get('type', 'Vulnerability')}", 0, 1)
                
                # Business Impact
                pdf.set_font('Arial', 'I', 10)
                pdf.set_text_color(51, 65, 85)
                impact = v.get('impact', 'This vulnerability poses a standard security risk.')
                pdf.multi_cell(0, 6, f"Business Risk: {impact}")
        else:
             pdf.ln(5)
             pdf.set_text_color(22, 163, 74)
             pdf.body_text("No critical business risks were identified during this scan.")

        pdf.ln(10)
        pdf.chapter_title("2. Executive Intelligence Summary")
        dynamic_text = generate_dynamic_summary(report_data)
        pdf.body_text(dynamic_text)
            
        pdf.ln(10)
        pdf.chapter_title("3. Strategic Remediation Roadmap")
        actions = generate_dynamic_actions(vulns)
        
        pdf.set_font('Arial', '', 11)
        pdf.set_text_color(51, 65, 85)
        for action in actions:
            pdf.cell(5, 8, chr(149), 0, 0) # Bullet point
            pdf.multi_cell(0, 8, action)

    # ================= TECHNICAL REPORT =================
    else:
        pdf.ln(5)
        pdf.chapter_title("1. Detailed Vulnerability Matrix")
        
        if not vulns:
            pdf.ln(5)
            pdf.body_text("No technical vulnerabilities detected.")
            
        for i, v in enumerate(vulns, 1):
            # Page break check
            if pdf.get_y() > 220: pdf.add_page()
            
            # --- Finding Header ---
            pdf.set_fill_color(241, 245, 249)
            pdf.set_draw_color(203, 213, 225)
            pdf.rect(10, pdf.get_y(), 190, 8, 'F')
            pdf.set_font('Arial', 'B', 10)
            pdf.set_text_color(15, 23, 42)
            pdf.cell(10, 8, str(i), 0, 0, 'C')
            pdf.cell(150, 8, v.get('type', 'Unknown'), 0, 0, 'L')
            
            # Severity Badge
            sev = v.get('severity', 'Low')
            if sev == 'Critical': pdf.set_text_color(220, 38, 38)
            elif sev == 'High': pdf.set_text_color(239, 68, 68)
            elif sev == 'Medium': pdf.set_text_color(249, 115, 22)
            else: pdf.set_text_color(22, 163, 74)
            pdf.cell(30, 8, sev.upper(), 0, 1, 'R')
            
            # --- Details ---
            pdf.ln(2)
            pdf.set_font('Arial', '', 10)
            pdf.set_text_color(51, 65, 85)
            
            # Location
            pdf.set_font('Arial', 'B', 9)
            pdf.cell(25, 6, "Location:", 0, 0)
            pdf.set_font('Arial', '', 9)
            pdf.cell(0, 6, v.get('url', 'N/A'), 0, 1)
            
            # Description
            desc = v.get('description', 'No description available.')
            pdf.multi_cell(0, 5, desc)
            pdf.ln(2)
            
            # --- Reproduction Steps (Grey Box) ---
            pdf.set_fill_color(248, 250, 252)
            pdf.set_draw_color(226, 232, 240)
            y_start = pdf.get_y()
            pdf.rect(10, y_start, 190, 25, 'FD') 
            
            pdf.set_xy(12, y_start + 2)
            pdf.set_font('Arial', 'B', 9)
            pdf.set_text_color(71, 85, 105)
            pdf.cell(0, 5, "Step-by-Step Reproduction / Proof of Concept:", 0, 1)
            
            pdf.set_font('Courier', '', 8)
            pdf.set_text_color(30, 41, 59)
            steps = v.get('reproduction', 'No reproduction steps provided.')
            pdf.multi_cell(186, 4, steps)
            
            # Reset Y to below the box
            pdf.set_y(y_start + 28)
            
            # --- Remediation (Green Border) ---
            pdf.set_draw_color(22, 163, 74) # Green
            pdf.set_line_width(0.2)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(2)
            
            pdf.set_font('Arial', 'B', 9)
            pdf.set_text_color(22, 163, 74)
            pdf.cell(25, 6, "REMEDIATION:", 0, 0)
            
            pdf.set_font('Arial', '', 9)
            pdf.set_text_color(51, 65, 85)
            fix = v.get('remediation', 'Please patch this issue immediately.')
            pdf.multi_cell(0, 6, fix)
            
            # --- NEW: CODE SNIPPET RENDERER ---
            code_snippet = v.get('fix')
            if code_snippet and "No code example" not in code_snippet:
                pdf.ln(4)
                pdf.set_font('Arial', 'B', 8)
                pdf.set_text_color(71, 85, 105) # Slate 600
                pdf.cell(0, 5, "SUGGESTED PATCH / CONFIGURATION:", 0, 1)
                pdf.draw_code_block(code_snippet)
            
            pdf.ln(8)

    # --- OUTPUT ---
    if not os.path.exists("reports"):
        os.makedirs("reports")
    
    target_clean = str(target).replace("http://", "").replace("https://", "")
    clean_name = re.sub(r'[\\/*?:"<>|]', '_', target_clean)
    suffix = "Executive" if report_type == 'executive' else "Technical"
    filename = f"reports/Sentinel_{suffix}_{clean_name}_{int(time.time())}.pdf"
    
    pdf.output(filename)
    return filename