from fpdf import FPDF
import time
import os
import re
import math

class AdvancedPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 10)
        self.set_text_color(100, 116, 139) # Slate 500
        self.cell(0, 10, 'CONFIDENTIAL SECURITY AUDIT', 0, 0, 'L')
        self.set_text_color(220, 38, 38) # Sentinel Red
        self.cell(0, 10, 'SENTINEL INTELLIGENCE', 0, 1, 'R')
        
        self.set_draw_color(220, 38, 38)
        self.set_line_width(0.5)
        self.line(10, 20, 200, 20)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by Sentinel', 0, 0, 'C')

    def draw_metric_card(self, x, y, w, h, title, value, subtitle, color):
        self.set_xy(x, y)
        self.set_fill_color(255, 255, 255)
        self.set_draw_color(226, 232, 240)
        self.rect(x, y, w, h, 'DF')
        self.set_fill_color(*color)
        self.rect(x, y, 2, h, 'F')
        
        self.set_xy(x + 5, y + 5)
        self.set_font('Arial', 'B', 9)
        self.set_text_color(148, 163, 184)
        self.cell(w-10, 5, title.upper(), 0, 2)
        
        self.set_font('Arial', 'B', 16)
        self.set_text_color(15, 23, 42)
        self.cell(w-10, 8, value, 0, 2)
        
        self.set_font('Arial', '', 7) # Smaller font for subtitle to fit
        self.set_text_color(100, 116, 139)
        self.cell(w-10, 5, subtitle, 0, 0)

    def draw_severity_chart(self, x, y, w, h, summary):
        total = summary['high'] + summary['medium'] + summary['low']
        if total == 0: total = 1
        
        high_w = (summary['high'] / total) * w
        med_w = (summary['medium'] / total) * w
        low_w = (summary['low'] / total) * w
        
        self.set_xy(x, y)
        self.set_fill_color(241, 245, 249)
        self.rect(x, y, w, h, 'F')
        
        current_x = x
        if high_w > 0:
            self.set_fill_color(220, 38, 38)
            self.rect(current_x, y, high_w, h, 'F')
            current_x += high_w
            
        if med_w > 0:
            self.set_fill_color(249, 115, 22)
            self.rect(current_x, y, med_w, h, 'F')
            current_x += med_w
            
        if low_w > 0:
            self.set_fill_color(22, 163, 74)
            self.rect(current_x, y, low_w, h, 'F')

        self.set_xy(x, y + h + 2)
        self.set_font('Arial', 'B', 8)
        self.set_text_color(100, 116, 139)
        self.cell(w, 5, f"THREAT LANDSCAPE: {int((summary['high']/total)*100)}% CRITICAL | {int((summary['medium']/total)*100)}% MODERATE | {int((summary['low']/total)*100)}% LOW", 0, 0, 'C')

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 14)
        self.set_text_color(15, 23, 42)
        self.cell(0, 10, label, 0, 1, 'L')
        self.ln(2)

    def body_text(self, text):
        self.set_font('Arial', '', 11)
        self.set_text_color(51, 65, 85)
        self.multi_cell(0, 6, text)
        self.ln()

# --- DYNAMIC BUSINESS INTELLIGENCE ---
def calculate_business_metrics(summary, vulnerabilities):
    # Base Calculation
    financial_risk = (summary['high'] * 75000) + (summary['medium'] * 15000) + (summary['low'] * 2000)
    
    # Dynamic Multipliers based on specific findings
    vuln_types = [v['type'].lower() for v in vulnerabilities]
    
    # Multiplier: Database Breach Risk
    if any("sql" in v for v in vuln_types):
        financial_risk *= 2.5 # SQLi is expensive (data dump)
        
    # Multiplier: PII (GDPR Fines)
    if any("pii" in v for v in vuln_types):
        financial_risk *= 1.5 
        
    # Multiplier: Infrastructure Compromise
    if any("secret" in v or "env" in v for v in vuln_types):
        financial_risk *= 3.0 # Full takeover risk

    hours = (summary['high'] * 12) + (summary['medium'] * 6) + (summary['low'] * 2)
    dev_days = max(1, math.ceil(hours / 8))
    
    prob = 10
    if summary['high'] > 0: prob = 95
    elif summary['medium'] > 2: prob = 75
    elif summary['medium'] > 0: prob = 45
    elif summary['low'] > 0: prob = 20
    
    return financial_risk, dev_days, prob

def get_grade_info(summary):
    if summary['high'] > 0:
        return "F", (220, 38, 38), "CRITICAL EXPOSURE", "Emergency Patching Required"
    elif summary['medium'] > 2:
        return "C", (249, 115, 22), "ELEVATED RISK", "Schedule Remediation Sprint"
    elif summary['medium'] > 0 or summary['low'] > 0:
        return "B", (234, 179, 8), "MODERATE HYGIENE", "hardening Required"
    else:
        return "A", (22, 163, 74), "SECURE", "Continuous Monitoring Active"

# --- NEW: CONTEXT-AWARE SUMMARY GENERATOR ---
def generate_dynamic_summary(report_data):
    summary = report_data.get('summary', {})
    vulns = report_data.get('vulnerabilities', [])
    vuln_types = [v['type'] for v in vulns]
    target = report_data.get('target', 'Target System')

    # 1. OPENING STATEMENT
    text = f"Sentinel Intelligence performed a deep-dive security audit on {target}. "
    if summary['high'] > 0:
        text += f"The system is currently in a CRITICAL state, with {summary['high']} high-severity vulnerabilities identified that pose an immediate threat to business continuity. "
    elif summary['medium'] > 0:
        text += f"The system demonstrates moderate security maturity but contains {summary['medium']} significant gaps that could be chained by attackers. "
    else:
        text += "The system demonstrates a strong security posture with no immediate critical threats detected. "

    # 2. SPECIFIC THREAT HIGHLIGHTS (The "Smart" Part)
    highlights = []
    
    # Check for SQL Injection
    if any("SQL" in t for t in vuln_types):
        highlights.append("CRITICAL: Database integrity is compromised. Active SQL Injection vectors were detected, allowing potential attackers to dump user data or modify records.")
        
    # Check for XSS
    if any("XSS" in t for t in vuln_types):
        highlights.append("Client-side security is weak. Reflected XSS vulnerabilities were found, which could lead to user session hijacking or phishing campaigns.")
        
    # Check for PII
    if any("PII" in t for t in vuln_types):
        highlights.append("PRIVACY ALERT: Personally Identifiable Information (PII) is being leaked in cleartext, posing a significant GDPR/CCPA compliance risk.")
        
    # Check for Secrets/.env
    if any("Sensitive File" in t or "Secret" in t for t in vuln_types):
        highlights.append("INFRASTRUCTURE LEAK: Critical configuration files (e.g., .env, backup.sql) are publicly accessible. This often leads to full server compromise.")

    # Check for Shadow APIs
    if any("Shadow API" in t for t in vuln_types):
        highlights.append("Undocumented 'Shadow APIs' were discovered. These endpoints often lack proper authentication checks compared to main API routes.")

    if highlights:
        text += "\n\nKEY FINDINGS:\n" + " ".join(highlights)
    else:
        text += "\n\nRoutine hygiene upgrades are recommended to maintain this status."

    # 3. CLOSING
    text += "\n\nIt is recommended to distribute the attached Technical Findings Matrix to the engineering team immediately."
    return text

def generate_dynamic_actions(vulns):
    actions = []
    vuln_types = [v['type'] for v in vulns]
    
    if any("SQL" in t for t in vuln_types):
        actions.append("URGENT: Implement Prepared Statements (Parameterized Queries) for all database interactions.")
    
    if any("Secret" in t or "File" in t for t in vuln_types):
        actions.append("IMMEDIATE: Rotate all API keys and database credentials. Configure server to block access to dotfiles (.env, .git).")
        
    if any("XSS" in t for t in vuln_types):
        actions.append("Sanitize all user inputs using a library like DOMPurify and implement a strict Content-Security-Policy (CSP).")
        
    if any("PII" in t for t in vuln_types):
        actions.append("Compliance: Redact email addresses and phone numbers from API responses.")
        
    if any("Shadow" in t for t in vuln_types):
        actions.append("Audit: Catalog detected Shadow APIs and enforce JWT authentication on these routes.")
        
    if not actions:
        actions.append("Conduct a quarterly penetration test.")
        actions.append("Review IAM permissions.")
        actions.append("Update third-party dependencies.")
        
    return actions

# --- AGGREGATION LOGIC ---
def aggregate_vulnerabilities(vulnerabilities):
    groups = {}
    for v in vulnerabilities:
        key = (v['type'], v['severity'], v['fix'])
        if key not in groups:
            groups[key] = {
                'type': v['type'], 'severity': v['severity'], 'fix': v['fix'], 'targets': []
            }
        if v['details'] not in groups[key]['targets']:
            groups[key]['targets'].append(v['details'])
    return list(groups.values())

# --- MAIN GENERATOR ---
def generate_report(report_data, report_type='technical'):
    pdf = AdvancedPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- HEADER ---
    title_prefix = "EXECUTIVE" if report_type == 'executive' else "TECHNICAL"
    pdf.set_font('Arial', 'B', 24)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, f"{title_prefix} AUDIT REPORT", 0, 1, 'L')
    
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 6, f"Target Asset: {report_data.get('target', 'Unknown')}", 0, 1, 'L')
    pdf.cell(0, 6, f"Scan Date: {time.strftime('%Y-%m-%d')}", 0, 1, 'L')
    pdf.ln(10)

    # --- GRADE CARD ---
    summary = report_data.get('summary', {'high': 0, 'medium': 0, 'low': 0})
    grade, color, grade_title, grade_action = get_grade_info(summary)
    
    pdf.set_fill_color(248, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    pdf.rect(10, pdf.get_y(), 190, 35, 'FD')
    
    current_y = pdf.get_y()
    pdf.set_fill_color(255, 255, 255)
    pdf.set_draw_color(*color)
    pdf.set_line_width(1)
    pdf.ellipse(13, current_y + 5.5, 24, 24, 'FD')
    
    pdf.set_xy(13, current_y + 11)
    pdf.set_font('Arial', 'B', 24)
    pdf.set_text_color(*color)
    pdf.cell(24, 13, grade, 0, 0, 'C')
    
    pdf.set_xy(45, current_y + 8)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(100, 6, grade_title, 0, 2)
    
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(100, 6, grade_action, 0, 0)
    pdf.ln(35) 

    # --- DYNAMIC METRICS ---
    pdf.ln(5)
    fin_risk, dev_days, prob = calculate_business_metrics(summary, report_data.get('vulnerabilities', []))
    
    start_x = 10
    card_w = 60
    card_h = 30
    gap = 5
    y_pos = pdf.get_y()
    
    pdf.draw_metric_card(start_x, y_pos, card_w, card_h, "Est. Financial Risk", f"${fin_risk:,.0f}", "Potential liability", (220, 38, 38))
    pdf.draw_metric_card(start_x + card_w + gap, y_pos, card_w, card_h, "Dev Time to Fix", f"{dev_days} Days", "Estimated effort", (249, 115, 22))
    pdf.draw_metric_card(start_x + (card_w + gap)*2, y_pos, card_w, card_h, "Breach Probability", f"{prob}%", "AI Risk Score", (37, 99, 235))
    
    pdf.set_y(y_pos + card_h + 10)

    # ================= EXECUTIVE MODE =================
    if report_type == 'executive':
        pdf.ln(5)
        pdf.chapter_title("Threat Visualization")
        pdf.draw_severity_chart(10, pdf.get_y(), 190, 8, summary)
        
        pdf.ln(15)
        pdf.chapter_title("Executive Intelligence Summary")
        # CALL DYNAMIC SUMMARY GENERATOR
        dynamic_text = generate_dynamic_summary(report_data)
        pdf.body_text(dynamic_text)
        
        pdf.ln(5)
        pdf.chapter_title("Strategic Remediation Roadmap")
        # CALL DYNAMIC ACTIONS GENERATOR
        actions = generate_dynamic_actions(report_data.get('vulnerabilities', []))
        
        pdf.set_font('Arial', '', 11)
        pdf.set_text_color(51, 65, 85)
        for action in actions:
            pdf.cell(5, 8, chr(149), 0, 0) # Bullet point
            pdf.multi_cell(0, 8, action)

    # ================= TECHNICAL MODE =================
    else:
        pdf.ln(5)
        pdf.chapter_title("Detailed Vulnerability Matrix")
        
        pdf.set_font('Arial', 'B', 10)
        pdf.set_fill_color(241, 245, 249)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(15, 10, "#", 1, 0, 'C', 1)
        pdf.cell(30, 10, "Severity", 1, 0, 'C', 1)
        pdf.cell(145, 10, "Finding", 1, 1, 'L', 1)
        
        pdf.set_font('Arial', '', 10)
        pdf.set_text_color(51, 65, 85)
        
        grouped_vulns = aggregate_vulnerabilities(report_data.get('vulnerabilities', []))
        
        if not grouped_vulns:
            pdf.ln(10)
            pdf.cell(190, 10, "System Clean. No vulnerabilities detected.", 1, 1, 'C')
        
        for i, vuln in enumerate(grouped_vulns, 1):
            sev = vuln['severity']
            if sev == 'Critical': pdf.set_text_color(220, 38, 38)
            elif sev == 'High': pdf.set_text_color(239, 68, 68)
            elif sev == 'Medium': pdf.set_text_color(249, 115, 22)
            else: pdf.set_text_color(22, 163, 74)
            
            pdf.ln(2)
            pdf.cell(15, 10, str(i), 1, 0, 'C')
            pdf.cell(30, 10, sev.upper(), 1, 0, 'C')
            
            pdf.set_text_color(15, 23, 42)
            title_text = vuln['type']
            if len(vuln['targets']) > 1:
                title_text += f" ({len(vuln['targets'])} instances)"
            
            pdf.cell(145, 10, title_text, 1, 1, 'L')
            
            # Details
            pdf.ln(1)
            pdf.set_x(25)
            pdf.set_font('Arial', '', 9)
            pdf.set_text_color(71, 85, 105)
            
            targets_str = "\n".join([f"- {t}" for t in vuln['targets'][:5]])
            if len(vuln['targets']) > 5: targets_str += "\n... (see full logs for more)"
            
            pdf.multi_cell(175, 5, f"Affected Endpoints:\n{targets_str}")
            
            # Code Fix Box
            pdf.ln(2)
            pdf.set_x(25)
            pdf.set_font('Courier', '', 8)
            pdf.set_fill_color(248, 250, 252)
            pdf.set_text_color(22, 163, 74)
            pdf.multi_cell(175, 5, f"FIX: {vuln['fix']}", 1, 'L', True)
            
            pdf.ln(3)
            pdf.set_font('Arial', '', 10)

    # --- OUTPUT ---
    if not os.path.exists("reports"):
        os.makedirs("reports")
    
    target_clean = report_data.get('target', 'unknown').replace("http://", "").replace("https://", "")
    clean_name = re.sub(r'[\\/*?:"<>|]', '_', target_clean)
    suffix = "Executive" if report_type == 'executive' else "Technical"
    filename = f"reports/Sentinel_{suffix}_{clean_name}_{int(time.time())}.pdf"
    
    pdf.output(filename)
    return filename